"""
Utils package - all utility functions
"""

from .file_handlers import (
    FileValidator,
    FileStorage,
    UploadHandler,
    ImageHandler,
    create_upload_response,
    init_file_handlers
)

from .validators import (
    ValidationResult,
    validate_email,
    validate_phone,
    validate_password,
    validate_username,
    validate_url,
    validate_date,
    validate_datetime,
    validate_future_date,
    validate_past_date,
    validate_number,
    validate_integer,
    validate_boolean,
    validate_uuid,
    validate_slug,
    validate_rating,
    validate_seats,
    validate_price,
    validate_json,
    validate_list,
    validate_dict,
    validate_required,
    validate_string,
    validate_file_extension,
    validate_file_size,
    validate_image,
    validate_credit_card,
    validate_cvv,
    validate_expiry_date,
    validate_event_date,
    validate_booking_quantity,
    validate_discount_code,
    sanitize_html,
    sanitize_input,
    sanitize_filename,
    ValidatorChain,
    ValidatorFactory,
    init_validators
)

from .helpers import (
    generate_token,
    generate_otp,
    generate_reference,
    hash_password,
    verify_password,
    get_current_user,
    get_current_user_id,
    is_admin,
    is_authenticated,
    admin_required,
    role_required,
    success_response,
    error_response,
    paginated_response,
    format_datetime,
    parse_datetime,
    get_time_ago,
    get_date_range,
    is_future_date,
    is_past_date,
    slugify,
    truncate_text,
    sanitize_html as sanitize_html_helper,
    extract_mentions,
    extract_hashtags,
    validate_email as validate_email_helper,
    validate_phone as validate_phone_helper,
    validate_url as validate_url_helper,
    validate_username as validate_username_helper,
    validate_password_strength,
    get_file_extension,
    is_allowed_file,
    generate_filename,
    get_file_size_str,
    generate_qr_code,
    generate_ticket_pdf,
    send_email,
    send_sms,
    dict_merge,
    flatten_dict,
    chunk_list,
    unique_list,
    generate_cache_key,
    memoize,
    get_client_ip,
    get_user_agent,
    is_ajax_request,
    get_request_data,
    log_activity,
    log_exception,
    generate_serial_number,
    get_week_number,
    get_quarter,
    get_fiscal_year,
    safe_divide,
    percentage,
    init_helpers
)

from .logger import (
    get_logger,
    get_access_logger,
    get_security_logger,
    get_performance_logger,
    get_database_logger,
    get_api_logger,
    get_error_logger,
    get_debug_logger,
    log_function,
    log_performance,
    log_exception as log_exception_decorator,
    log_time,
    LogContext,
    PerformanceContext,
    LogUtils,
    FlaskLogger,
    init_logger,
    test_logging
)

from .notification import (
    NotificationType,
    Priority,
    Channel,
    NotificationStatus,
    NotificationData,
    NotificationTemplate,
    NotificationService,
    get_notification_service,
    send_booking_confirmation,
    send_event_reminder,
    send_payment_confirmation,
    send_event_cancelled,
    send_password_reset,
    send_email_verification,
    send_welcome_email,
    send_ticket_available,
    send_review_response,
    send_event_reminders_batch,
    send_booking_reminders_batch,
    get_user_notifications,
    get_unread_count,
    mark_notification_read,
    mark_all_notifications_read,
    delete_notification,
    delete_all_notifications,
    init_notification_service
)

from .error_handlers import (
    AppException,
    ValidationError,
    AuthenticationError,
    AuthorizationError,
    NotFoundError,
    ConflictError,
    RateLimitError,
    ServerError,
    DatabaseError,
    PaymentError,
    BusinessLogicError,
    FileUploadError,
    EmailError,
    ErrorResponseFormatter,
    register_error_handlers,
    handle_validation_errors,
    create_validation_error_response,
    get_error_code,
    get_status_code,
    is_client_error,
    is_server_error,
    ErrorContext,
    handle_errors,
    log_errors,
    init_error_handlers
)

from .middleware import (
    timing_middleware,
    cache_middleware,
    retry_middleware,
    rate_limit_middleware,
    validate_json_middleware,
    role_required_middleware,
    log_request_middleware,
    error_handler_middleware,
    RequestValidator,
    validate_request_middleware,
    PerformanceMiddleware,
    CacheControlMiddleware,
    CompressionMiddleware,
    SecurityHeadersMiddleware,
    RateLimiter,
    RequestIDMiddleware,
    IPBlockMiddleware,
    UserAgentBlockMiddleware,
    CORSMiddleware,
    init_utils_middleware
)

__version__ = '1.0.0'

__all__ = [
    # File handlers
    'FileValidator', 'FileStorage', 'UploadHandler', 'ImageHandler',
    'create_upload_response', 'init_file_handlers',
    
    # Validators
    'ValidationResult', 'validate_email', 'validate_phone', 'validate_password',
    'validate_username', 'validate_url', 'validate_date', 'validate_datetime',
    'validate_future_date', 'validate_past_date', 'validate_number',
    'validate_integer', 'validate_boolean', 'validate_uuid', 'validate_slug',
    'validate_rating', 'validate_seats', 'validate_price', 'validate_json',
    'validate_list', 'validate_dict', 'validate_required', 'validate_string',
    'validate_file_extension', 'validate_file_size', 'validate_image',
    'validate_credit_card', 'validate_cvv', 'validate_expiry_date',
    'validate_event_date', 'validate_booking_quantity', 'validate_discount_code',
    'sanitize_html', 'sanitize_input', 'sanitize_filename',
    'ValidatorChain', 'ValidatorFactory', 'init_validators',
    
    # Helpers
    'generate_token', 'generate_otp', 'generate_reference',
    'hash_password', 'verify_password',
    'get_current_user', 'get_current_user_id', 'is_admin', 'is_authenticated',
    'admin_required', 'role_required',
    'success_response', 'error_response', 'paginated_response',
    'format_datetime', 'parse_datetime', 'get_time_ago', 'get_date_range',
    'is_future_date', 'is_past_date',
    'slugify', 'truncate_text', 'sanitize_html_helper',
    'extract_mentions', 'extract_hashtags',
    'validate_email_helper', 'validate_phone_helper',
    'validate_url_helper', 'validate_username_helper',
    'validate_password_strength',
    'get_file_extension', 'is_allowed_file', 'generate_filename',
    'get_file_size_str',
    'generate_qr_code', 'generate_ticket_pdf',
    'send_email', 'send_sms',
    'dict_merge', 'flatten_dict', 'chunk_list', 'unique_list',
    'generate_cache_key', 'memoize',
    'get_client_ip', 'get_user_agent', 'is_ajax_request', 'get_request_data',
    'log_activity', 'log_exception',
    'generate_serial_number', 'get_week_number', 'get_quarter',
    'get_fiscal_year', 'safe_divide', 'percentage',
    'init_helpers',
    
    # Logger
    'get_logger', 'get_access_logger', 'get_security_logger',
    'get_performance_logger', 'get_database_logger', 'get_api_logger',
    'get_error_logger', 'get_debug_logger',
    'log_function', 'log_performance', 'log_exception_decorator', 'log_time',
    'LogContext', 'PerformanceContext',
    'LogUtils', 'FlaskLogger', 'init_logger', 'test_logging',
    
    # Notification
    'NotificationType', 'Priority', 'Channel', 'NotificationStatus',
    'NotificationData', 'NotificationTemplate', 'NotificationService',
    'get_notification_service',
    'send_booking_confirmation', 'send_event_reminder',
    'send_payment_confirmation', 'send_event_cancelled',
    'send_password_reset', 'send_email_verification', 'send_welcome_email',
    'send_ticket_available', 'send_review_response',
    'send_event_reminders_batch', 'send_booking_reminders_batch',
    'get_user_notifications', 'get_unread_count',
    'mark_notification_read', 'mark_all_notifications_read',
    'delete_notification', 'delete_all_notifications',
    'init_notification_service',
    
    # Error handlers
    'AppException', 'ValidationError', 'AuthenticationError',
    'AuthorizationError', 'NotFoundError', 'ConflictError',
    'RateLimitError', 'ServerError', 'DatabaseError',
    'PaymentError', 'BusinessLogicError', 'FileUploadError', 'EmailError',
    'ErrorResponseFormatter', 'register_error_handlers',
    'handle_validation_errors', 'create_validation_error_response',
    'get_error_code', 'get_status_code',
    'is_client_error', 'is_server_error',
    'ErrorContext', 'handle_errors', 'log_errors',
    'init_error_handlers',
    
    # Middleware
    'timing_middleware', 'cache_middleware', 'retry_middleware',
    'rate_limit_middleware', 'validate_json_middleware',
    'role_required_middleware', 'log_request_middleware',
    'error_handler_middleware',
    'RequestValidator', 'validate_request_middleware',
    'PerformanceMiddleware', 'CacheControlMiddleware',
    'CompressionMiddleware', 'SecurityHeadersMiddleware',
    'RateLimiter', 'RequestIDMiddleware',
    'IPBlockMiddleware', 'UserAgentBlockMiddleware',
    'CORSMiddleware', 'init_utils_middleware'
]